
---

# Step 1: Validation of Variables
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - postgresql_version
  - postgresql_port
  - postgresql_user
  - postgresql_password
  - postgresql_group
  - postgresql_service_name
  - postgresql_packages
  - postgresql_data_directory
  - postgresql_bin_directory
  - postgresql_conf
  - postgresql_dependencies
  - postgresql_apt_repository_url


# Step 2: Add PostgreSQL repository
- name: Add PostgreSQL APT repository
  block:
    - name: Add APT signing key
      apt_key:
        url: "{{ postgresql_apt_repository_key }}"
        keyring: "/etc/apt/trusted.gpg.d/postgresql.gpg"
        state: present
      become: yes
        
    - name: Add repo
      apt_repository:
        repo: "deb {{ postgresql_apt_repository_url }}"
        state: present
        filename: postgresql
      become: yes

# Step 3: Update APT cache
- name: Update APT cache
  apt:
    update_cache: yes
  become: yes

# Step 4: Install PostgreSQL dependencies
- name: Install PostgreSQL dependencies
  apt:
    name: "{{ postgresql_dependencies }}"
    state: present
  become: yes

# Step 5: Install PostgreSQL
- name: Install PostgreSQL
  apt:
    name: "{{ postgresql_packages }}"
    state: present
  become: yes

- name: copy pg_hba.conf template
  template:
    src: pg_hba.conf.j2
    dest: "/etc/postgresql/{{ postgresql_version }}/main/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: 0644
  become: yes
  register: postgresql_configuration_1

- name: uncomment postgresql properties
  replace:
    path: "{{ postgresql_conf_file }}"
    regexp: "^#({{ item.key }})"
    replace: '\1'
  with_dict: "{{ postgresql_conf }}"
  become: yes

- name: update postgresql.conf file
  lineinfile:
    path: "{{ postgresql_conf_file }}"
    line: "{{ item.key }} = {{ item.value }}"
    regexp: "^{{ item.key | replace('.', '\\.') }} ="
  with_dict: "{{ postgresql_conf }}"
  become: yes
  register: postgresql_configuration_2

- name: Ensure the pid directory for PostgreSQL exists
  file:
    name: "{{ postgresql_pid_directory }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: u=rwX,g=rwXs,o=rx
  become: yes
  notify: restart postgresql

# Step 8: Stop older PostgreSQL services

- name: check old posgtres services
  shell: "systemctl list-unit-files --type=service | grep postgresql | grep -v {{ postgresql_service_name }} | awk '{print $1}'"
  register: old_services
  become: yes
  changed_when: no

- name: stop old postgresql services
  service:
    name: "{{ item }}"
    state: stopped
    enabled: no
  with_items: "{{ old_services.stdout_lines }}"
  become: yes
  when: old_services.stdout_lines | length > 0

# Step 9: Reload PostgreSQL Configuration

- name: Reload all conf files
  service:
    name: "{{ postgresql_service_name }}"
    state: reloaded
  become: yes
  when: postgresql_configuration_1.changed or postgresql_configuration_2.changed

# Step 10: Update PostgreSQL Password

- name: Ensure PostgreSQL is started and enabled on boot.
  service:
    name: "{{ postgresql_service_name }}"
    state: "started"
    enabled: yes
  become: yes

- name: Update the password of the postgres user
  command: psql -U postgres -d postgres -c "alter user postgres with password '{{ postgresql_password }}';"
  become: yes
  become_user: "{{ postgresql_user }}"
  changed_when: no

- name: restart service
  service:
    name: "{{ postgresql_service_name }}"
    state: restarted
    enabled: yes
  become: yes

# Step 11: Expose Role Output

- name: sanitize role name
  set_fact:
    sanitize_role_name: "{{ role_name | replace('-', '_') | regex_replace('([^A-Za-z0-9_])', '') | trim }}"

- name: expose role output
  set_fact:
    "{{ sanitize_role_name }}":
      postgresql_version: "{{ postgresql_version }}"
      postgresql_host: "{{ ansible_default_ipv4.address }}"
      postgresql_user: "{{ postgresql_user }}"
      postgresql_password: "{{ postgresql_password }}"
      postgresql_port: "{{ postgresql_port }}"
      postgresql_service_name: "{{ postgresql_service_name }}"
  become: yes
